prediction:
  model_path: src/main/resources/model.bin
  statistics_path: src/main/resources/statistics.bin
  synergy_matrix_path: src/main/resources/synergy.txt
  counter_matrix_path: src/main/resources/counter.txt

server:
  error:
    include-message: always